# Generated by Django 6.0.5 on 2026-07-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblstudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idno', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('courseid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblstudents',
            },
        ),
    ]
