# Generated by Django 6.0.5 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudents',
            name='idno',
            field=models.CharField(max_length=50),
        ),
    ]
