# Generated by Django 6.0.7 on 2026-08-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_tblstudents_idno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudents',
            name='enrollment_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default='regular', max_length=20),
        ),
    ]
