# Generated by Django 6.0.5 on 2026-07-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcourse',
            fields=[
                ('courseid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('schoolyr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblcourse',
            },
        ),
    ]
