# Generated by Django 6.0.5 on 2026-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcourse',
            name='courseid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
