# Generated by Django 6.0.7 on 2026-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_tblcourse_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcourse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
