# Generated by Django 6.0.7 on 2026-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('identification', 'Identification'), ('true_false', 'True/False'), ('multiple_choice', 'Multiple Choice')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
