# Generated by Django 5.0.14 on 2026-09-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assign_course_ownership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
