# Generated by Django 6.0.5 on 2026-07-29 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblattendance',
            fields=[
                ('attend_id', models.AutoField(primary_key=True, serialize=False)),
                ('attend_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.tblstudents')),
            ],
            options={
                'db_table': 'tblattendance',
            },
        ),
    ]
